import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import { AnalysisResult, Message } from "@/types/analysis";

export const generateAlphaReport = (idea: string, result: AnalysisResult) => {
    const doc = new jsPDF();

    // Header
    doc.setFillColor(15, 23, 42); // Dark slate
    doc.rect(0, 0, 210, 40, "F");
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(22);
    doc.text("SYNTIX ALPHA REPORT", 105, 25, { align: "center" });

    // Idea Section
    doc.setTextColor(0, 0, 0);
    doc.setFontSize(14);
    doc.text("Business Concept:", 14, 50);
    doc.setFontSize(11);
    doc.text(doc.splitTextToSize(idea, 180), 14, 60);

    // Scores
    doc.setFontSize(14);
    doc.text("Investment Readiness Analysis", 14, 90);

    const scoreData = [
        ["Metric", "Score", "Status"],
        ["IRL Score", `${result.score}/100`, getStatus(result.score)],
        ["Logical Coherence", `${result.detailedScores?.logicalCoherence || 0}/100`, getStatus(result.detailedScores?.logicalCoherence || 0)],
        ["Market Depth", `${result.detailedScores?.marketDepth || 0}/100`, getStatus(result.detailedScores?.marketDepth || 0)],
        ["Unit Economics", `${result.detailedScores?.unitEconomics || 0}/100`, getStatus(result.detailedScores?.unitEconomics || 0)],
    ];

    autoTable(doc, {
        startY: 95,
        head: [scoreData[0]],
        body: scoreData.slice(1),
        theme: 'grid',
        headStyles: { fillColor: [15, 23, 42] },
    });

    // Radar Data Summary
    const radarStart = (doc as any).lastAutoTable.finalY + 15;
    doc.text("Radar Dimensions", 14, radarStart);

    const radarRows = result.radarData.map(r => [r.subject, `${r.A}/150`]);

    autoTable(doc, {
        startY: radarStart + 5,
        head: [["Dimension", "Score"]],
        body: radarRows,
        theme: 'striped',
        headStyles: { fillColor: [71, 85, 105] },
    });

    // Qualitative Feedback
    const feedbackStart = (doc as any).lastAutoTable.finalY + 15;
    doc.text("The Auditor's Verdict", 14, feedbackStart);
    doc.setFontSize(10);
    doc.setFont("courier", "normal");
    doc.text(doc.splitTextToSize(result.feedback, 180), 14, feedbackStart + 8);

    // Footer
    doc.setFont("helvetica", "italic");
    doc.setFontSize(8);
    doc.text(`Generated by Syntix AI on ${new Date().toLocaleDateString()}`, 105, 290, { align: "center" });

    doc.save("syntix-alpha-report.pdf");
};

export const generateBetaReport = (idea: string, result: AnalysisResult, chatHistory: Message[]) => {
    const doc = new jsPDF();

    // Header (Beta Color - slightly different?)
    doc.setFillColor(30, 41, 59); // Slightly lighter slate
    doc.rect(0, 0, 210, 40, "F");
    doc.setTextColor(0, 255, 157); // Accent Green
    doc.setFontSize(22);
    doc.text("SYNTIX BETA REPORT", 105, 25, { align: "center" });

    // Idea Section
    doc.setTextColor(0, 0, 0);
    doc.setFontSize(14);
    doc.text("Refined Concept:", 14, 50);
    doc.setFontSize(11);
    doc.setFont("helvetica", "normal");
    doc.text(doc.splitTextToSize(idea, 180), 14, 60);

    // Scores Summary
    doc.setFontSize(14);
    doc.text("Base Metrics", 14, 85);

    autoTable(doc, {
        startY: 90,
        head: [["IRL Score", "Market Depth", "Unit Econ"]],
        body: [[
            result.score,
            result.detailedScores?.marketDepth || 0,
            result.detailedScores?.unitEconomics || 0
        ]],
        theme: 'plain',
    });

    // Chat History Section / Advisor Recommendations
    const chatStart = (doc as any).lastAutoTable.finalY + 15;

    // RECOMMENDATIONS BULLETS
    doc.setFontSize(14);
    doc.text("Strategic Recommendations", 14, chatStart);

    // Extract advisor messages for "bullet points" simulation
    const advisorMessages = chatHistory
        .filter(m => m.role !== 'user' && m.role !== 'system')
        .map(m => `• [${m.persona?.toUpperCase() || 'ADVISOR'}]: ${m.content.substring(0, 100).replace(/\n/g, ' ')}...`);

    if (advisorMessages.length > 0) {
        doc.setFontSize(10);
        doc.setFont("helvetica", "normal");
        let yPos = chatStart + 8;
        advisorMessages.forEach(msg => {
            doc.text(msg, 20, yPos);
            yPos += 6;
        });

        // Push transcript down
        (doc as any).lastAutoTable.finalY = yPos + 10;
    }

    // FULL TRANSCRIPT
    const transcriptStart = (doc as any).lastAutoTable.finalY + 5;
    doc.setFontSize(12);
    doc.setFont("helvetica", "bold");
    doc.text("Full Board Transcript", 14, transcriptStart);

    const chatRows = chatHistory.filter(m => m.role !== 'system').map(msg => {
        const role = msg.role === 'user' ? 'Founder' : msg.persona?.toUpperCase() || 'AI';
        return [role, msg.content];
    });

    autoTable(doc, {
        startY: transcriptStart + 5,
        head: [["Speaker", "Dialogue"]],
        body: chatRows,
        theme: 'grid',
        columnStyles: {
            0: { fontStyle: 'bold', cellWidth: 40, fillColor: [240, 240, 240] },
            1: { cellWidth: 140 }
        },
        headStyles: { fillColor: [30, 41, 59] },
    });

    // Footer
    doc.setFont("helvetica", "italic");
    doc.setFontSize(8);
    doc.text(`Generated by Syntix AI on ${new Date().toLocaleDateString()}`, 105, 290, { align: "center" });

    doc.save(`syntix-beta-report-${Date.now()}.pdf`);
};

function getStatus(score: number) {
    if (score >= 80) return "UNICORN POTENTIAL";
    if (score >= 50) return "VIABLE";
    return "PIVOT REQUIRED";
}
