"use client";

import { createContext, useContext, useState, ReactNode } from "react";

type Language = "pt" | "en";

const translations = {
  en: {
    nav: {
      vault: "Vault",
      upload: "Upload",
      family: "Family",
      sharedWithMe: "Shared With Me",
      processingTimes: "Processing Times",
      settings: "Settings",
      notifications: "Notifications",
      agent: "Agent Dashboard",
      login: "Sign In",
      logout: "Sign Out",
    },
    common: {
      loading: "Loading...",
      save: "Save",
      cancel: "Cancel",
      delete: "Delete",
      share: "Share",
      download: "Download",
      close: "Close",
      confirm: "Confirm",
      search: "Search",
      noResults: "No results found",
      back: "Back",
    },
    vault: {
      title: "Document Vault",
      subtitle: "Your secure travel document manager",
      dashboard: "Dashboard",
      totalDocuments: "Total Documents",
      expiringSoon: "Expiring Soon",
      expired: "Expired",
      sharedDocuments: "Shared Documents",
      uploadDocument: "Upload Document",
      noDocuments: "No documents yet. Upload your first travel document.",
      documentTypes: {
        PASSPORT: "Passport",
        VISA: "Visa",
        INSURANCE: "Travel Insurance",
        VACCINATION: "Vaccination Card",
        OTHER: "Other",
      },
      status: {
        safe: "Valid",
        warning: "Expiring Soon",
        danger: "Expires Soon",
        expired: "Expired",
      },
    },
    upload: {
      title: "Upload Document",
      selectFile: "Select File",
      dragDrop: "or drag and drop",
      maxSize: "Max file size: 25MB",
      documentType: "Document Type",
      label: "Label",
      labelPlaceholder: "e.g. Brazilian Passport",
      expiryDate: "Expiry Date",
      assignTo: "Assign To",
      myself: "Myself",
      encrypting: "Encrypting...",
      uploading: "Uploading...",
      success: "Document uploaded and encrypted successfully!",
    },
    family: {
      title: "Family Documents",
      addMember: "Add Family Member",
      memberName: "Name",
      relationship: "Relationship",
      relationships: {
        SPOUSE: "Spouse",
        CHILD: "Child",
        PARENT: "Parent",
        SIBLING: "Sibling",
        OTHER: "Other",
      },
      noMembers: "No family members yet.",
      documentsCount: "documents",
      nextExpiry: "Next expiry",
    },
    sharing: {
      title: "Shared With Me",
      shareWith: "Share with",
      emailPlaceholder: "Enter recipient email",
      accessLevel: "Access Level",
      viewOnly: "View Only",
      viewAndDownload: "View & Download",
      expires: "Expires",
      revoke: "Revoke Access",
      noShares: "No documents shared with you yet.",
      sharedBy: "Shared by",
    },
    processing: {
      title: "Processing Times",
      subtitle: "Estimated times from travel agents",
      documentType: "Document Type",
      country: "Country",
      city: "Consulate City",
      days: "days",
      source: "Source",
      reportedBy: "Reported by",
      noData: "No processing time data yet.",
      sources: {
        POLICIA_FEDERAL: "Policia Federal",
        CONSULATE: "Consulate",
        AGENT_EXPERIENCE: "Agent Experience",
      },
    },
    passphrase: {
      title: "Vault Passphrase",
      description: "Enter your passphrase to unlock the vault.",
      setTitle: "Create Vault Passphrase",
      setDescription:
        "Choose a strong passphrase to encrypt your documents. This passphrase cannot be recovered if lost.",
      enter: "Enter Passphrase",
      set: "Set Passphrase",
      confirm: "Confirm Passphrase",
      unlock: "Unlock Vault",
      lock: "Lock Vault",
      mismatch: "Passphrases do not match",
      warning:
        "This passphrase CANNOT be recovered. If you lose it, your documents will be permanently inaccessible.",
      placeholder: "Enter your vault passphrase",
    },
    consent: {
      title: "Data Processing Consent",
      description:
        "TravelVault encrypts and stores your travel documents. Before proceeding, please review and accept our data processing terms.",
      dataProcessing: "I consent to the processing of my encrypted travel documents for storage and reminder purposes.",
      crossBorder: "I understand my encrypted data may be stored in servers outside my country of residence, protected by Standard Contractual Clauses.",
      terms: "I accept the Terms of Service and Privacy Policy.",
      accept: "I Accept & Continue",
      decline: "Decline",
      required: "All consents are required to use the vault.",
    },
    reminders: {
      title: "Reminders",
      set: "Set Reminder",
      daysBefore: "days before expiry",
      active: "Active Reminders",
      noReminders: "No active reminders",
      options: {
        30: "30 days before",
        60: "60 days before",
        90: "90 days before",
        180: "180 days before",
      },
    },
    tiers: {
      free: "Free",
      premium: "Premium",
      agent: "Travel Agent",
      upgrade: "Upgrade",
      limitReached: "You've reached the limit for your plan.",
      documentsLeft: "documents remaining",
    },
    settings: {
      title: "Settings",
      changePassphrase: "Change Passphrase",
      exportData: "Export My Data",
      exportDescription: "Download all your encrypted documents and metadata.",
      deleteAccount: "Delete My Vault",
      deleteDescription: "Permanently delete all your vault data. This cannot be undone.",
      dpo: "Data Protection Officer",
      dpoContact: "For LGPD/GDPR inquiries: dpo@travelvault.app",
      consentHistory: "Consent History",
    },
    landing: {
      hero: "Your Travel Documents, Encrypted & Organized",
      subtitle: "Zero-knowledge encryption. Expiry reminders. Family management. LGPD & GDPR compliant.",
      cta: "Get Started — Free",
      features: {
        encrypt: "End-to-End Encrypted",
        encryptDesc: "Documents encrypted before they leave your device. We can never see them.",
        reminders: "Smart Reminders",
        remindersDesc: "Never miss a passport or visa renewal deadline again.",
        family: "Family Mode",
        familyDesc: "Manage documents for your whole family in one place.",
        share: "Selective Sharing",
        shareDesc: "Share specific documents with your travel agent — never with groups.",
        compliance: "LGPD & GDPR Compliant",
        complianceDesc: "Full data ownership, export, and deletion rights.",
        processing: "Processing Times",
        processingDesc: "Know how long visas and passports take, sourced from travel agents.",
      },
    },
  },
  pt: {
    nav: {
      vault: "Cofre",
      upload: "Enviar",
      family: "Família",
      sharedWithMe: "Compartilhados Comigo",
      processingTimes: "Prazos de Processamento",
      settings: "Configurações",
      notifications: "Notificações",
      agent: "Painel do Agente",
      login: "Entrar",
      logout: "Sair",
    },
    common: {
      loading: "Carregando...",
      save: "Salvar",
      cancel: "Cancelar",
      delete: "Excluir",
      share: "Compartilhar",
      download: "Baixar",
      close: "Fechar",
      confirm: "Confirmar",
      search: "Buscar",
      noResults: "Nenhum resultado encontrado",
      back: "Voltar",
    },
    vault: {
      title: "Cofre de Documentos",
      subtitle: "Seu gerenciador seguro de documentos de viagem",
      dashboard: "Painel",
      totalDocuments: "Total de Documentos",
      expiringSoon: "Vencendo em Breve",
      expired: "Vencidos",
      sharedDocuments: "Documentos Compartilhados",
      uploadDocument: "Enviar Documento",
      noDocuments: "Nenhum documento ainda. Envie seu primeiro documento de viagem.",
      documentTypes: {
        PASSPORT: "Passaporte",
        VISA: "Visto",
        INSURANCE: "Seguro Viagem",
        VACCINATION: "Cartão de Vacinação",
        OTHER: "Outro",
      },
      status: {
        safe: "Válido",
        warning: "Vencendo em Breve",
        danger: "Vence em Breve",
        expired: "Vencido",
      },
    },
    upload: {
      title: "Enviar Documento",
      selectFile: "Selecionar Arquivo",
      dragDrop: "ou arraste e solte",
      maxSize: "Tamanho máximo: 25MB",
      documentType: "Tipo de Documento",
      label: "Rótulo",
      labelPlaceholder: "ex: Passaporte Brasileiro",
      expiryDate: "Data de Validade",
      assignTo: "Atribuir a",
      myself: "Eu mesmo",
      encrypting: "Criptografando...",
      uploading: "Enviando...",
      success: "Documento enviado e criptografado com sucesso!",
    },
    family: {
      title: "Documentos da Família",
      addMember: "Adicionar Membro",
      memberName: "Nome",
      relationship: "Parentesco",
      relationships: {
        SPOUSE: "Cônjuge",
        CHILD: "Filho(a)",
        PARENT: "Pai/Mãe",
        SIBLING: "Irmão(ã)",
        OTHER: "Outro",
      },
      noMembers: "Nenhum membro da família ainda.",
      documentsCount: "documentos",
      nextExpiry: "Próximo vencimento",
    },
    sharing: {
      title: "Compartilhados Comigo",
      shareWith: "Compartilhar com",
      emailPlaceholder: "Digite o email do destinatário",
      accessLevel: "Nível de Acesso",
      viewOnly: "Apenas Visualizar",
      viewAndDownload: "Visualizar e Baixar",
      expires: "Expira em",
      revoke: "Revogar Acesso",
      noShares: "Nenhum documento compartilhado com você ainda.",
      sharedBy: "Compartilhado por",
    },
    processing: {
      title: "Prazos de Processamento",
      subtitle: "Tempos estimados por agentes de viagem",
      documentType: "Tipo de Documento",
      country: "País",
      city: "Cidade do Consulado",
      days: "dias",
      source: "Fonte",
      reportedBy: "Reportado por",
      noData: "Nenhum dado de prazo ainda.",
      sources: {
        POLICIA_FEDERAL: "Polícia Federal",
        CONSULATE: "Consulado",
        AGENT_EXPERIENCE: "Experiência do Agente",
      },
    },
    passphrase: {
      title: "Senha do Cofre",
      description: "Digite sua senha para desbloquear o cofre.",
      setTitle: "Criar Senha do Cofre",
      setDescription:
        "Escolha uma senha forte para criptografar seus documentos. Esta senha não pode ser recuperada se perdida.",
      enter: "Digite a Senha",
      set: "Definir Senha",
      confirm: "Confirmar Senha",
      unlock: "Desbloquear Cofre",
      lock: "Bloquear Cofre",
      mismatch: "As senhas não conferem",
      warning:
        "Esta senha NÃO pode ser recuperada. Se você a perder, seus documentos ficarão permanentemente inacessíveis.",
      placeholder: "Digite a senha do cofre",
    },
    consent: {
      title: "Consentimento de Tratamento de Dados",
      description:
        "O TravelVault criptografa e armazena seus documentos de viagem. Antes de continuar, revise e aceite nossos termos de tratamento de dados.",
      dataProcessing: "Eu consinto com o tratamento dos meus documentos de viagem criptografados para fins de armazenamento e lembretes.",
      crossBorder: "Eu entendo que meus dados criptografados podem ser armazenados em servidores fora do meu país de residência, protegidos por Cláusulas Contratuais Padrão.",
      terms: "Eu aceito os Termos de Serviço e a Política de Privacidade.",
      accept: "Aceitar e Continuar",
      decline: "Recusar",
      required: "Todos os consentimentos são necessários para usar o cofre.",
    },
    reminders: {
      title: "Lembretes",
      set: "Definir Lembrete",
      daysBefore: "dias antes do vencimento",
      active: "Lembretes Ativos",
      noReminders: "Nenhum lembrete ativo",
      options: {
        30: "30 dias antes",
        60: "60 dias antes",
        90: "90 dias antes",
        180: "180 dias antes",
      },
    },
    tiers: {
      free: "Gratuito",
      premium: "Premium",
      agent: "Agente de Viagem",
      upgrade: "Atualizar",
      limitReached: "Você atingiu o limite do seu plano.",
      documentsLeft: "documentos restantes",
    },
    settings: {
      title: "Configurações",
      changePassphrase: "Alterar Senha",
      exportData: "Exportar Meus Dados",
      exportDescription: "Baixe todos os seus documentos criptografados e metadados.",
      deleteAccount: "Excluir Meu Cofre",
      deleteDescription: "Exclua permanentemente todos os dados do cofre. Esta ação não pode ser desfeita.",
      dpo: "Encarregado de Proteção de Dados",
      dpoContact: "Para questões LGPD/GDPR: dpo@travelvault.app",
      consentHistory: "Histórico de Consentimento",
    },
    landing: {
      hero: "Seus Documentos de Viagem, Criptografados e Organizados",
      subtitle: "Criptografia de conhecimento zero. Lembretes de vencimento. Gestão familiar. Conforme LGPD e GDPR.",
      cta: "Comece Agora — Grátis",
      features: {
        encrypt: "Criptografia Ponta a Ponta",
        encryptDesc: "Documentos criptografados antes de sair do seu dispositivo. Nós nunca podemos vê-los.",
        reminders: "Lembretes Inteligentes",
        remindersDesc: "Nunca mais perca o prazo de renovação de passaporte ou visto.",
        family: "Modo Família",
        familyDesc: "Gerencie documentos de toda a família em um só lugar.",
        share: "Compartilhamento Seletivo",
        shareDesc: "Compartilhe documentos específicos com seu agente de viagem — nunca com grupos.",
        compliance: "Conforme LGPD e GDPR",
        complianceDesc: "Propriedade total dos dados, exportação e direito à exclusão.",
        processing: "Prazos de Processamento",
        processingDesc: "Saiba quanto tempo levam vistos e passaportes, informado por agentes de viagem.",
      },
    },
  },
};

type Translations = (typeof translations)["en"];

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: Translations;
}

const LanguageContext = createContext<LanguageContextType>({
  language: "en",
  setLanguage: () => {},
  t: translations.en,
});

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>("en");
  const t = translations[language];

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
